start-infra:
 podman run --ulimit memlock=-1:-1 -d -it --rm=true --name=todo-database \
        -e POSTGRES_USER=todos \
        -e POSTGRES_PASSWORD=todos \
        -e POSTGRES_DB=todos \
        -p 5432:5432 postgres:16-alpine

stop-infra:
    podman stop todo-database

restart-infra: stop-infra start-infra

start-spring-jvm mem="128m":
    cd todo-app-spring  && java -Xmx{{mem}} -Xms{{mem}} -Dspring.profiles.active=production -jar target/todo-app-spring-1.0-SNAPSHOT.jar

start-spring-native mem="64m":
    cd todo-app-spring  && ./target/todo-app-spring -Xmx{{mem}} -Xms{{mem}} -Dspring.profiles.active=production

start-quarkus-jvm mem="128m":
    cd todo-app-quarkus  && java -Xmx{{mem}} -Xms{{mem}} -jar target/quarkus-app/quarkus-run.jar

start-quarkus-native mem="64m":
    cd todo-app-quarkus  && ./target/todo-app-quarkus-1.0-SNAPSHOT-runner -Xmx{{mem}} -Xms{{mem}}

dev-spring:
    ./mvnw spring-boot:run -f todo-app-spring

dev-quarkus:
    ./mvnw quarkus:dev -f todo-app-quarkus

build-quarkus-native:
    ./mvnw package -Pnative -DskipTests -f todo-app-quarkus

build-spring-native:
    ./mvnw native:compile -Pnative -DskipTests -f todo-app-spring

build-quarkus-jvm:
    ./mvnw package -DskipTests -f todo-app-quarkus

build-spring-jvm:
    ./mvnw package -DskipTests -f todo-app-spring

tell-me-the-diff:
    diff -Naur todo-app-spring/src/main/java todo-app-quarkus/src/main/java

populate host:
    curl -H "Content-Type: application/json" {{host}}/api
    curl -X POST -H "Content-Type: application/json" -d '{"title":"Todo 1"}' {{host}}/api
    curl -X POST -H "Content-Type: application/json" -d '{"title":"Todo 2"}' {{host}}/api
    curl -X POST -H "Content-Type: application/json" -d '{"title":"Todo 3"}' {{host}}/api
    # Add and complete a todo
    curl -s -X POST -H "Content-Type: application/json" -d '{"title":"Todo 5"}' {{host}}/api | jq '.id' | xargs -I {} curl -X PATCH -H "Content-Type: application/json" -d '{"completed":true, "title": "Todo 5"}' {{host}}/api/{}

load host:
    wrk.sh --latency --timeout 1s -t 2 -c 40 -d 10s {{host}}/api

